- src/Cocorico/CoreBundle/Resources/doc/index.rst
For crons 5 and 6, the last parameter (day of week) was missing.
> Fix cron docs

- .travis.yml
- README.md
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Tests pass?   | yes
| Fixed issues  | NA
This PR enable Travis-CI integration with basic linter tests
> added minimal tests (linter)

- CHANGELOG.md
- src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/ListingAvailabilityPriceController.php
- src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/ListingAvailabilityStatusController.php
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Tests pass?   | yes
| Fixed issues  | 
Add error message on listing calendar edition
> Add error message on listing calendar edition

- CHANGELOG.md
- app/Resources/translations/cocorico.en.xliff
- app/Resources/translations/cocorico.fr.xliff
- src/Cocorico/CoreBundle/Helper/GlobalHelper.php
- src/Cocorico/CoreBundle/Resources/config/Services/twig_extensions.yml
- src/Cocorico/CoreBundle/Twig/CoreExtension.php
- src/Cocorico/CoreBundle/Utils/PHP.php
- src/Cocorico/PageBundle/Controller/Frontend/PageController.php
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
- Move some GlobalHelper methods to Utils\PHP class
> Move some GlobalHelper methods to Utils\PHP class

- src/Cocorico/CoreBundle/Controller/Frontend/ListingFavouriteController.php
- src/Cocorico/CoreBundle/Controller/Frontend/ListingSearchController.php
| Branch?       | master / x
| Bug fix?      | yes
| New feature?  | yes/no
| Tests pass?   | yes/no
| Fixed issues  | #135 
- Error when add to Favourite
> Fix bug Error when add to Favourite

- src/Cocorico/CoreBundle/Resources/config/config.yml
- src/Cocorico/GeoBundle/Resources/views/Common/js/_geocoding_js.html.twig
| New feature?  | [ x ]
Restrict geolocation for a defined country
> Add counties filtering in gmap autocomplete field

- README.md
- src/Cocorico/CoreBundle/Controller/Frontend/ListingSearchController.php
Fix similar listings session persisting
> Fix similar listings session persisting

- src/Cocorico/ReviewBundle/Model/ReviewManager.php
Fix change reviewer images in reviews list
> Fix change reviewer images in reviews list

- src/Cocorico/CoreBundle/Resources/views/Frontend/Listing/similar_listing.html.twig
Strip private info in similar listing
> Strip private info in similar listing

- src/Cocorico/UserBundle/Form/Type/RegistrationFormType.php
> Replace ChoiceType::class by 'choice'

- CHANGELOG.md
- LICENSE
- src/Cocorico/CoreBundle/Resources/config/parameters.yml
> Remove unused parameters

- src/Cocorico/CoreBundle/Resources/views/Dashboard/Listing/edit_location.html.twig
Add form errors in edit listing location
> Add form errors in edit listing location

- src/Cocorico/UserBundle/Controller/Dashboard/ProfileAboutMeController.php
> edit action renamed

- src/Cocorico/CoreBundle/Model/Manager/BookingPayinRefundManager.php
Fix refund amount with 3 decimals
> Fix refund amount with 3 decimals

- src/Cocorico/CoreBundle/Controller/Frontend/BookingController.php
- src/Cocorico/CoreBundle/Form/Handler/Frontend/BookingFormHandler.php
- src/Cocorico/CoreBundle/Resources/config/Services/subscribers.yml
Add BookingSubscriber for new booking
> Add BookingSubscriber for new booking

- app/Resources/translations/SonataAdminBundle.en.xliff
- app/Resources/translations/SonataAdminBundle.fr.xliff
- app/Resources/translations/cocorico.en.xliff
- app/Resources/translations/cocorico.fr.xliff
- app/Resources/translations/cocorico_booking.en.xliff
- app/Resources/translations/cocorico_booking.fr.xliff
- app/Resources/translations/routes.en.xliff
- app/Resources/translations/routes.fr.xliff
- src/Cocorico/CoreBundle/Event/BookingSubscriber.php
- src/Cocorico/CoreBundle/Resources/config/parameters.yml
- src/Cocorico/CoreBundle/Resources/views/Frontend/Booking/_amounts.html.twig
- src/Cocorico/CoreBundle/Resources/views/Frontend/Booking/_form_new.html.twig
- src/Cocorico/CoreBundle/Resources/views/Frontend/Booking/_side.html.twig
- src/Cocorico/CoreBundle/Resources/views/Frontend/Booking/new.html.twig
- src/Cocorico/CoreBundle/Security/Voter/BookingVoter.php
Update for MangopayBundle v0.5 compatibility
> Update for MangopayBundle v0.5 compatibility

- app/config/parameters.yml.dist
- src/Cocorico/ConfigBundle/Resources/views/list_parameter_value.html.twig
- src/Cocorico/CoreBundle/Admin/ListingAdmin.php
- src/Cocorico/CoreBundle/Resources/config/Services/twig_extensions.yml
- src/Cocorico/CoreBundle/Resources/config/config.yml
- src/Cocorico/CoreBundle/Resources/config/parameters.yml
- src/Cocorico/CoreBundle/Twig/TranslationExtension.php
- web/css/all-override.css
- web/css/all.css
Add translations checking functionality
> Add translations checking functionality

- CHANGELOG.md
- src/Cocorico/CoreBundle/Model/Manager/ListingAvailabilityManager.php
- src/Cocorico/CoreBundle/Resources/views/Frontend/Booking/form_booking_price.html.twig
> Enhance booking button in booking price form

- src/Cocorico/CoreBundle/Controller/Frontend/ListingController.php
- src/Cocorico/CoreBundle/Repository/ListingRepository.php
Add 301 redirect to listing show URL when slug has changed
> Add 301 redirect to listing show URL when slug has changed

- src/Cocorico/CoreBundle/Twig/TranslationExtension.php
Fix warning messages while route translations extractions
> Fix warning messages while route translations extractions

- src/Cocorico/CoreBundle/Admin/ListingCategoryAdmin.php
- src/Cocorico/CoreBundle/Twig/CoreExtension.php
Fix categories export in sonata
> Fix categories export in sonata

- src/Cocorico/CoreBundle/Resources/views/Frontend/Home/index.html.twig
- src/Cocorico/CoreBundle/Resources/views/Frontend/Listing/show.html.twig
- src/Cocorico/CoreBundle/Resources/views/Frontend/ListingResult/result.html.twig
- src/Cocorico/UserBundle/Resources/views/Frontend/Profile/show.html.twig
Add JS escaping on initMultiSelect
> Add JS escaping on initMultiSelect

- app/config/parameters.yml.dist
- src/Cocorico/CoreBundle/Model/ListingSearchRequest.php
- src/Cocorico/CoreBundle/Repository/ListingRepository.php
- src/Cocorico/CoreBundle/Resources/views/Frontend/Common/form_search_fields.html.twig
- src/Cocorico/CoreBundle/Resources/views/Frontend/Home/form_search_fields.html.twig
- web/css/all-override.css
- web/js/common.js
Merge branch 'elasticsearchev' into dev
> Add CocoricoElasticSearchBundle compatibility

- src/Cocorico/UserBundle/Entity/UserLanguage.php
Fix user language code too short
> Fix user language code too short

- bin/start-elasticsearch.bat
Add Elastic search starting script
> Add Elastic search starting script

- src/Cocorico/CoreBundle/Resources/views/Form/fields.html.twig
> Add time range form errors

- src/Cocorico/CoreBundle/DataFixtures/ORM/2_LoadUserData.php
- src/Cocorico/CoreBundle/Mailer/TwigSwiftMailer.php
Set phoneVerified to false by default in user fixtures
> Set phoneVerified to false by default in user fixtures

- src/Cocorico/CoreBundle/Resources/views/Frontend/Home/rss_feed.html.twig
Fix feed blocks on HP if no feed items
> Fix feed blocks on HP if no feed items

- src/Cocorico/CoreBundle/Resources/views/Frontend/Common/js/_facebook_js.html.twig
> Update Facebook SDK version

- src/Cocorico/CoreBundle/Resources/config/parameters.yml
Add Elasticsearch Bundle custom parameters
> Add Elasticsearch Bundle custom parameters

- src/Cocorico/CoreBundle/Command/MigrateBookingsDatesCommand.php
Update migration script for times date equal to 1970-01-01
> Update migration script for times date equal to 1970-01-01

- src/Cocorico/CoreBundle/Twig/CountryExtension.php
- src/Cocorico/CoreBundle/Twig/ExtraBundleExtension.php
- src/Cocorico/CoreBundle/Twig/LanguageExtension.php
- src/Cocorico/ReviewBundle/Extension/StarRatingTwigExtension.php
- src/Cocorico/TimeBundle/Twig/IntlExtension.php
Fix Twig extensions getGlobals
> Fix Twig extensions getGlobals

- src/Cocorico/CoreBundle/Admin/ListingAdmin.php
- src/Cocorico/CoreBundle/Entity/Listing.php
- src/Cocorico/SonataAdminBundle/Resources/views/impersonating.html.twig
- src/Cocorico/UserBundle/Admin/UserAdmin.php
- src/Cocorico/UserBundle/Entity/User.php
> Fix impersonating in admin

- src/Cocorico/CoreBundle/Controller/Dashboard/Asker/BookingController.php
- src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/BookingController.php
- src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/ListingAvailabilityPriceController.php
- src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/ListingAvailabilityStatusController.php
- src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/ListingCategoriesAjaxController.php
- src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/ListingCategoriesController.php
- src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/ListingCharacteristicController.php
- src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/ListingController.php
- src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/ListingDiscountController.php
- src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/ListingImageController.php
- src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/ListingLocationController.php
- src/Cocorico/CoreBundle/Controller/Dashboard/Offerer/ListingPresentationController.php
> $selfUrl variable is deleted

- src/Cocorico/CoreBundle/Security/Voter/BookingVoter.php
- src/Cocorico/CoreBundle/Security/Voter/ListingImageVoter.php
- src/Cocorico/CoreBundle/Security/Voter/ListingVoter.php
- src/Cocorico/ReviewBundle/Security/Voter/ReviewVoter.php
- src/Cocorico/UserBundle/Security/Voter/UserImageVoter.php
| Bug fix?      | [X ]
| Fixed issues  | #366
> Updated voters for SF3.4

- doc/installation-windows.md
> Fix url (virtual-hosts.md)

- src/Cocorico/CoreBundle/Form/Type/CountryFilteredType.php
- src/Cocorico/CoreBundle/Form/Type/Dashboard/ListingEditAvailabilitiesType.php
- src/Cocorico/CoreBundle/Form/Type/Dashboard/ListingEditDiscountType.php
- src/Cocorico/CoreBundle/Form/Type/Frontend/BookingNewType.php
- src/Cocorico/CoreBundle/Form/Type/Frontend/BookingPriceType.php
- src/Cocorico/CoreBundle/Form/Type/Frontend/BookingUserAddressFormType.php
- src/Cocorico/CoreBundle/Form/Type/Frontend/ListingLocationSearchType.php
- src/Cocorico/CoreBundle/Form/Type/Frontend/ListingNewCategoriesType.php
- src/Cocorico/CoreBundle/Form/Type/Frontend/ListingNewType.php
- src/Cocorico/CoreBundle/Form/Type/Frontend/ListingSearchHomeType.php
- src/Cocorico/CoreBundle/Form/Type/Frontend/ListingSearchType.php
- src/Cocorico/CoreBundle/Form/Type/ImageType.php
- src/Cocorico/CoreBundle/Form/Type/NumberRangeType.php
- src/Cocorico/CoreBundle/Form/Type/PriceRangeType.php
- src/Cocorico/CoreBundle/Form/Type/PriceType.php
- src/Cocorico/GeoBundle/Form/Type/GeocodingToCoordinateType.php
- src/Cocorico/MessageBundle/Form/Type/Frontend/ReplyMessageFormType.php
- src/Cocorico/TimeBundle/Form/Type/DateRangeType.php
- src/Cocorico/TimeBundle/Form/Type/TimeRangeType.php
- src/Cocorico/UserBundle/Form/Type/UserAddressFormType.php
- src/Cocorico/UserBundle/Form/Type/UserLanguageType.php
Remove depreciated getName in form types
> Remove depreciated getName in form types

- app/config/config_dev.yml
- src/Cocorico/CMSBundle/Resources/config/services.yml
- src/Cocorico/CoreBundle/Resources/config/Services/entities_manager.yml
- src/Cocorico/CoreBundle/Resources/config/config.yml
- src/Cocorico/CoreBundle/Resources/config/services.yml
- src/Cocorico/MessageBundle/Resources/config/services.yml
- src/Cocorico/UserBundle/Admin/UserAddressAdmin.php
- src/Cocorico/UserBundle/Resources/config/config.yml
> Fix some SF 3.4 deprecations

- app/AppKernel.php
- src/Cocorico/SonataUserBundle/CocoricoSonataUserBundle.php
- src/Cocorico/SonataUserBundle/Resources/views/Admin/Security/login.html.twig
> Override Sonata User Bundle

- src/Cocorico/GeoBundle/Resources/views/Common/js/_geocoding_js.html.twig
> Fix js escaping

- src/Cocorico/CoreBundle/Form/Type/CountryFilteredType.php
- src/Cocorico/CoreBundle/Form/Type/EntityHiddenType.php
- src/Cocorico/CoreBundle/Form/Type/LanguageFilteredType.php
- src/Cocorico/CoreBundle/Form/Type/ListingCategoryType.php
- src/Cocorico/GeoBundle/Form/Type/GeocodingToCoordinateType.php
- src/Cocorico/TimeBundle/Form/Type/DateHiddenType.php
| Bug fix?      | [ X ]
| Fixed issues  |
Finish form update to symfony 3.4
> Added FQCN on form getParent methods

- src/Cocorico/ConfigBundle/Admin/ParameterAdmin.php
- src/Cocorico/ContactBundle/Controller/Frontend/ContactController.php
- web/robots.txt
> Remove unnecessary variables
